// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: bike_rpc/bike.proto

package bike_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetBikesRequest) Reset() {
	*x = GetBikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_rpc_bike_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBikesRequest) ProtoMessage() {}

func (x *GetBikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bike_rpc_bike_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBikesRequest.ProtoReflect.Descriptor instead.
func (*GetBikesRequest) Descriptor() ([]byte, []int) {
	return file_bike_rpc_bike_proto_rawDescGZIP(), []int{0}
}

func (x *GetBikesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bikes []*Bike `protobuf:"bytes,1,rep,name=bikes,proto3" json:"bikes,omitempty"`
}

func (x *GetBikesResponse) Reset() {
	*x = GetBikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_rpc_bike_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBikesResponse) ProtoMessage() {}

func (x *GetBikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_rpc_bike_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBikesResponse.ProtoReflect.Descriptor instead.
func (*GetBikesResponse) Descriptor() ([]byte, []int) {
	return file_bike_rpc_bike_proto_rawDescGZIP(), []int{1}
}

func (x *GetBikesResponse) GetBikes() []*Bike {
	if x != nil {
		return x.Bikes
	}
	return nil
}

type AddBikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bike *Bike `protobuf:"bytes,1,opt,name=bike,proto3" json:"bike,omitempty"`
}

func (x *AddBikeRequest) Reset() {
	*x = AddBikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_rpc_bike_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBikeRequest) ProtoMessage() {}

func (x *AddBikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bike_rpc_bike_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBikeRequest.ProtoReflect.Descriptor instead.
func (*AddBikeRequest) Descriptor() ([]byte, []int) {
	return file_bike_rpc_bike_proto_rawDescGZIP(), []int{2}
}

func (x *AddBikeRequest) GetBike() *Bike {
	if x != nil {
		return x.Bike
	}
	return nil
}

type AddBikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeID string `protobuf:"bytes,1,opt,name=BikeID,proto3" json:"BikeID,omitempty"`
}

func (x *AddBikeResponse) Reset() {
	*x = AddBikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_rpc_bike_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBikeResponse) ProtoMessage() {}

func (x *AddBikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_rpc_bike_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBikeResponse.ProtoReflect.Descriptor instead.
func (*AddBikeResponse) Descriptor() ([]byte, []int) {
	return file_bike_rpc_bike_proto_rawDescGZIP(), []int{3}
}

func (x *AddBikeResponse) GetBikeID() string {
	if x != nil {
		return x.BikeID
	}
	return ""
}

type Bike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeID       string `protobuf:"bytes,1,opt,name=BikeID,proto3" json:"BikeID,omitempty"`
	UserID       string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ModelName    string `protobuf:"bytes,3,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	PurchaseDate string `protobuf:"bytes,4,opt,name=PurchaseDate,proto3" json:"PurchaseDate,omitempty"`
}

func (x *Bike) Reset() {
	*x = Bike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_rpc_bike_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bike) ProtoMessage() {}

func (x *Bike) ProtoReflect() protoreflect.Message {
	mi := &file_bike_rpc_bike_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bike.ProtoReflect.Descriptor instead.
func (*Bike) Descriptor() ([]byte, []int) {
	return file_bike_rpc_bike_proto_rawDescGZIP(), []int{4}
}

func (x *Bike) GetBikeID() string {
	if x != nil {
		return x.BikeID
	}
	return ""
}

func (x *Bike) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Bike) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Bike) GetPurchaseDate() string {
	if x != nil {
		return x.PurchaseDate
	}
	return ""
}

var File_bike_rpc_bike_proto protoreflect.FileDescriptor

var file_bike_rpc_bike_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x69, 0x6b, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x69, 0x6b, 0x65, 0x22, 0x2a, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x69,
	0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x62,
	0x69, 0x6b, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x69, 0x6b,
	0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x05, 0x62, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x30, 0x0a,
	0x0e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x04, 0x62, 0x69, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x62, 0x69, 0x6b, 0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x04, 0x62, 0x69, 0x6b, 0x65, 0x22,
	0x29, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x6b, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x42, 0x69, 0x6b, 0x65, 0x49, 0x44, 0x22, 0x78, 0x0a, 0x04, 0x42, 0x69,
	0x6b, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x6b, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x42, 0x69, 0x6b, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x65, 0x32, 0x80, 0x01, 0x0a, 0x0b, 0x42, 0x69, 0x6b, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73,
	0x12, 0x15, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6b, 0x65, 0x12, 0x14, 0x2e, 0x62, 0x69, 0x6b,
	0x65, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6b, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x6f, 0x6c, 0x6b, 0x69, 0x65, 0x6e, 0x52, 0x6f, 0x6f,
	0x6c, 0x73, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2f, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x72, 0x70, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bike_rpc_bike_proto_rawDescOnce sync.Once
	file_bike_rpc_bike_proto_rawDescData = file_bike_rpc_bike_proto_rawDesc
)

func file_bike_rpc_bike_proto_rawDescGZIP() []byte {
	file_bike_rpc_bike_proto_rawDescOnce.Do(func() {
		file_bike_rpc_bike_proto_rawDescData = protoimpl.X.CompressGZIP(file_bike_rpc_bike_proto_rawDescData)
	})
	return file_bike_rpc_bike_proto_rawDescData
}

var file_bike_rpc_bike_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bike_rpc_bike_proto_goTypes = []interface{}{
	(*GetBikesRequest)(nil),  // 0: bike.GetBikesRequest
	(*GetBikesResponse)(nil), // 1: bike.GetBikesResponse
	(*AddBikeRequest)(nil),   // 2: bike.AddBikeRequest
	(*AddBikeResponse)(nil),  // 3: bike.AddBikeResponse
	(*Bike)(nil),             // 4: bike.Bike
}
var file_bike_rpc_bike_proto_depIdxs = []int32{
	4, // 0: bike.GetBikesResponse.bikes:type_name -> bike.Bike
	4, // 1: bike.AddBikeRequest.bike:type_name -> bike.Bike
	0, // 2: bike.BikeService.GetBikes:input_type -> bike.GetBikesRequest
	2, // 3: bike.BikeService.AddBike:input_type -> bike.AddBikeRequest
	1, // 4: bike.BikeService.GetBikes:output_type -> bike.GetBikesResponse
	3, // 5: bike.BikeService.AddBike:output_type -> bike.AddBikeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bike_rpc_bike_proto_init() }
func file_bike_rpc_bike_proto_init() {
	if File_bike_rpc_bike_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bike_rpc_bike_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_rpc_bike_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_rpc_bike_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_rpc_bike_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_rpc_bike_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bike_rpc_bike_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bike_rpc_bike_proto_goTypes,
		DependencyIndexes: file_bike_rpc_bike_proto_depIdxs,
		MessageInfos:      file_bike_rpc_bike_proto_msgTypes,
	}.Build()
	File_bike_rpc_bike_proto = out.File
	file_bike_rpc_bike_proto_rawDesc = nil
	file_bike_rpc_bike_proto_goTypes = nil
	file_bike_rpc_bike_proto_depIdxs = nil
}
