// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bike

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BikeServiceClient is the client API for BikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BikeServiceClient interface {
	// Получить полную информацию о велосипеде
	GetBikeDetails(ctx context.Context, in *BikeRequest, opts ...grpc.CallOption) (*BikeResponse, error)
	// Обновить состояние компонента
	UpdateComponentStatus(ctx context.Context, in *ComponentStatusUpdate, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type bikeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBikeServiceClient(cc grpc.ClientConnInterface) BikeServiceClient {
	return &bikeServiceClient{cc}
}

func (c *bikeServiceClient) GetBikeDetails(ctx context.Context, in *BikeRequest, opts ...grpc.CallOption) (*BikeResponse, error) {
	out := new(BikeResponse)
	err := c.cc.Invoke(ctx, "/bike.BikeService/GetBikeDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bikeServiceClient) UpdateComponentStatus(ctx context.Context, in *ComponentStatusUpdate, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/bike.BikeService/UpdateComponentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BikeServiceServer is the server API for BikeService service.
// All implementations must embed UnimplementedBikeServiceServer
// for forward compatibility
type BikeServiceServer interface {
	// Получить полную информацию о велосипеде
	GetBikeDetails(context.Context, *BikeRequest) (*BikeResponse, error)
	// Обновить состояние компонента
	UpdateComponentStatus(context.Context, *ComponentStatusUpdate) (*UpdateResponse, error)
	mustEmbedUnimplementedBikeServiceServer()
}

// UnimplementedBikeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBikeServiceServer struct {
}

func (UnimplementedBikeServiceServer) GetBikeDetails(context.Context, *BikeRequest) (*BikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBikeDetails not implemented")
}
func (UnimplementedBikeServiceServer) UpdateComponentStatus(context.Context, *ComponentStatusUpdate) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComponentStatus not implemented")
}
func (UnimplementedBikeServiceServer) mustEmbedUnimplementedBikeServiceServer() {}

// UnsafeBikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BikeServiceServer will
// result in compilation errors.
type UnsafeBikeServiceServer interface {
	mustEmbedUnimplementedBikeServiceServer()
}

func RegisterBikeServiceServer(s grpc.ServiceRegistrar, srv BikeServiceServer) {
	s.RegisterService(&BikeService_ServiceDesc, srv)
}

func _BikeService_GetBikeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BikeServiceServer).GetBikeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bike.BikeService/GetBikeDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BikeServiceServer).GetBikeDetails(ctx, req.(*BikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BikeService_UpdateComponentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComponentStatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BikeServiceServer).UpdateComponentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bike.BikeService/UpdateComponentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BikeServiceServer).UpdateComponentStatus(ctx, req.(*ComponentStatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

// BikeService_ServiceDesc is the grpc.ServiceDesc for BikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bike.BikeService",
	HandlerType: (*BikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBikeDetails",
			Handler:    _BikeService_GetBikeDetails_Handler,
		},
		{
			MethodName: "UpdateComponentStatus",
			Handler:    _BikeService_UpdateComponentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bike.proto",
}
