// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: bike.proto

package bike

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentStatus int32

const (
	ComponentStatus_UNKNOWN           ComponentStatus = 0
	ComponentStatus_GOOD              ComponentStatus = 1
	ComponentStatus_NEEDS_MAINTENANCE ComponentStatus = 2
	ComponentStatus_DAMAGED           ComponentStatus = 3
)

// Enum value maps for ComponentStatus.
var (
	ComponentStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "GOOD",
		2: "NEEDS_MAINTENANCE",
		3: "DAMAGED",
	}
	ComponentStatus_value = map[string]int32{
		"UNKNOWN":           0,
		"GOOD":              1,
		"NEEDS_MAINTENANCE": 2,
		"DAMAGED":           3,
	}
)

func (x ComponentStatus) Enum() *ComponentStatus {
	p := new(ComponentStatus)
	*p = x
	return p
}

func (x ComponentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bike_proto_enumTypes[0].Descriptor()
}

func (ComponentStatus) Type() protoreflect.EnumType {
	return &file_bike_proto_enumTypes[0]
}

func (x ComponentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentStatus.Descriptor instead.
func (ComponentStatus) EnumDescriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{0}
}

type BikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BikeId string `protobuf:"bytes,1,opt,name=bike_id,json=bikeId,proto3" json:"bike_id,omitempty"`
}

func (x *BikeRequest) Reset() {
	*x = BikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeRequest) ProtoMessage() {}

func (x *BikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeRequest.ProtoReflect.Descriptor instead.
func (*BikeRequest) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{0}
}

func (x *BikeRequest) GetBikeId() string {
	if x != nil {
		return x.BikeId
	}
	return ""
}

type BikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bike *Bike `protobuf:"bytes,1,opt,name=bike,proto3" json:"bike,omitempty"`
}

func (x *BikeResponse) Reset() {
	*x = BikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeResponse) ProtoMessage() {}

func (x *BikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeResponse.ProtoReflect.Descriptor instead.
func (*BikeResponse) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{1}
}

func (x *BikeResponse) GetBike() *Bike {
	if x != nil {
		return x.Bike
	}
	return nil
}

type Bike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model      string       `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Components []*Component `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
}

func (x *Bike) Reset() {
	*x = Bike{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bike) ProtoMessage() {}

func (x *Bike) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bike.ProtoReflect.Descriptor instead.
func (*Bike) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{2}
}

func (x *Bike) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bike) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Bike) GetComponents() []*Component {
	if x != nil {
		return x.Components
	}
	return nil
}

type Component struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SerialNumber    string          `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Status          ComponentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=bike.ComponentStatus" json:"status,omitempty"`
	LastMaintenance string          `protobuf:"bytes,4,opt,name=last_maintenance,json=lastMaintenance,proto3" json:"last_maintenance,omitempty"`
}

func (x *Component) Reset() {
	*x = Component{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{3}
}

func (x *Component) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Component) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Component) GetStatus() ComponentStatus {
	if x != nil {
		return x.Status
	}
	return ComponentStatus_UNKNOWN
}

func (x *Component) GetLastMaintenance() string {
	if x != nil {
		return x.LastMaintenance
	}
	return ""
}

type ComponentStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ComponentId string          `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	NewStatus   ComponentStatus `protobuf:"varint,2,opt,name=new_status,json=newStatus,proto3,enum=bike.ComponentStatus" json:"new_status,omitempty"`
}

func (x *ComponentStatusUpdate) Reset() {
	*x = ComponentStatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatusUpdate) ProtoMessage() {}

func (x *ComponentStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatusUpdate.ProtoReflect.Descriptor instead.
func (*ComponentStatusUpdate) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{4}
}

func (x *ComponentStatusUpdate) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ComponentStatusUpdate) GetNewStatus() ComponentStatus {
	if x != nil {
		return x.NewStatus
	}
	return ComponentStatus_UNKNOWN
}

type UpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bike_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bike_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_bike_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bike_proto protoreflect.FileDescriptor

var file_bike_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x69,
	0x6b, 0x65, 0x22, 0x26, 0x0a, 0x0b, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x6b, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x6b, 0x65, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x0c, 0x42, 0x69,
	0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x69,
	0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e,
	0x42, 0x69, 0x6b, 0x65, 0x52, 0x04, 0x62, 0x69, 0x6b, 0x65, 0x22, 0x5d, 0x0a, 0x04, 0x42, 0x69,
	0x6b, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x2f, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62,
	0x69, 0x6b, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x9e, 0x01, 0x0a, 0x09, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x29, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x4d,
	0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x70, 0x0a, 0x15, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x62, 0x69, 0x6b,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x44, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2a, 0x4c, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f, 0x4f, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x4e, 0x45, 0x45, 0x44, 0x53, 0x5f, 0x4d, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43,
	0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x41, 0x4d, 0x41, 0x47, 0x45, 0x44, 0x10, 0x03,
	0x32, 0x92, 0x01, 0x0a, 0x0b, 0x42, 0x69, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x37, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6b, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x11, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x42, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1b, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a,
	0x14, 0x2e, 0x62, 0x69, 0x6b, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bike_proto_rawDescOnce sync.Once
	file_bike_proto_rawDescData = file_bike_proto_rawDesc
)

func file_bike_proto_rawDescGZIP() []byte {
	file_bike_proto_rawDescOnce.Do(func() {
		file_bike_proto_rawDescData = protoimpl.X.CompressGZIP(file_bike_proto_rawDescData)
	})
	return file_bike_proto_rawDescData
}

var file_bike_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bike_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bike_proto_goTypes = []interface{}{
	(ComponentStatus)(0),          // 0: bike.ComponentStatus
	(*BikeRequest)(nil),           // 1: bike.BikeRequest
	(*BikeResponse)(nil),          // 2: bike.BikeResponse
	(*Bike)(nil),                  // 3: bike.Bike
	(*Component)(nil),             // 4: bike.Component
	(*ComponentStatusUpdate)(nil), // 5: bike.ComponentStatusUpdate
	(*UpdateResponse)(nil),        // 6: bike.UpdateResponse
}
var file_bike_proto_depIdxs = []int32{
	3, // 0: bike.BikeResponse.bike:type_name -> bike.Bike
	4, // 1: bike.Bike.components:type_name -> bike.Component
	0, // 2: bike.Component.status:type_name -> bike.ComponentStatus
	0, // 3: bike.ComponentStatusUpdate.new_status:type_name -> bike.ComponentStatus
	1, // 4: bike.BikeService.GetBikeDetails:input_type -> bike.BikeRequest
	5, // 5: bike.BikeService.UpdateComponentStatus:input_type -> bike.ComponentStatusUpdate
	2, // 6: bike.BikeService.GetBikeDetails:output_type -> bike.BikeResponse
	6, // 7: bike.BikeService.UpdateComponentStatus:output_type -> bike.UpdateResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bike_proto_init() }
func file_bike_proto_init() {
	if File_bike_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bike_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bike); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Component); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentStatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bike_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bike_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bike_proto_goTypes,
		DependencyIndexes: file_bike_proto_depIdxs,
		EnumInfos:         file_bike_proto_enumTypes,
		MessageInfos:      file_bike_proto_msgTypes,
	}.Build()
	File_bike_proto = out.File
	file_bike_proto_rawDesc = nil
	file_bike_proto_goTypes = nil
	file_bike_proto_depIdxs = nil
}
